### ISSUE TITLE
Normative grammar ambiguities

### ISSUE THREAD

**Issue by zaach** [lloyd/orderly#1]
I was building a bottom-up parser based on your grammar and I believe I ran across some issues:
- The regex for the `property_name` rule doesn't include numerals though the descriptions notes it includes "alphanumerics"
- The nonterminal `optional_extra_properties` doesn't have an epsilon rule, though it should be optional, right?
- The `definition_suffix` rule includes the `optional_additional_marker`, though it is already included in the `definition_prefix` for objects and arrays, which are the only two types that allow it. So, it should be removed from `definition_suffix`.
- Lastly, in your [example](http://orderly-json.org/), the top level entry is unnamed, though the `orderly_schema` nonterminal only includes `named_entry`, which would disallow unnamed entries at the top level.

Let me know what you make of these ambiguities, and if I have misinterpreted anything. Thanks!

**Comment by zaach** [comment]
Oh, also
    optional_requires
        '<' csv_property_name '>'
        # nothing
should be
    optional_requires
        '<' csv_property_names '>'
        # nothing

**Comment by lloyd** [comment]
fix ambiguities in grammar found by Zach Carter, and break documentation into a separate markdown document.  Closed by d7fda34dde07d24745d71695b42f309133deed71

**Comment by lloyd** [comment]
hey zach, thank you for the careful read and taking the time to report.  very excited to check out the javascript implementation :)
